### ISSUE TITLE
[Feature] Ignore Neutral mobs in MoveAlongPathModel Step

### ISSUE THREAD

**Issue by Dreamzlol** [Talamin/Wholesome-Dungeon-Crawler#18]
If you die as example and a neutral mob is in the way without the tank or other members being there because the Mob was not in the pull range at the time or respawned when he passed that spot the Bot tends to stuck and waiting forever to be all members be there. Or we have a Feature like if we stuck at a certain time we port out and back in so all members are together again.
I had this problem alot in TBC Dungeons.

![Untitled-2](https://user-images.githubusercontent.com/92863811/180604820-71048ac7-07ff-4ea4-990c-406d77905714.jpg)

**Comment by MrCeeJ** [comment]
We ignore them now :)
